
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Longitude = -122.22F,
    Latitude = 37.86F,
    Housing_median_age = 21F,
    Total_rooms = 7099F,
    Total_bedrooms = 1106F,
    Population = 2401F,
    Households = 1138F,
    Median_income = 8.3014F,
    Ocean_proximity = @"NEAR BAY",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Median_house_value with predicted Median_house_value from sample data...\n\n");


Console.WriteLine($"Longitude: {-122.22F}");
Console.WriteLine($"Latitude: {37.86F}");
Console.WriteLine($"Housing_median_age: {21F}");
Console.WriteLine($"Total_rooms: {7099F}");
Console.WriteLine($"Total_bedrooms: {1106F}");
Console.WriteLine($"Population: {2401F}");
Console.WriteLine($"Households: {1138F}");
Console.WriteLine($"Median_income: {8.3014F}");
Console.WriteLine($"Median_house_value: {358500F}");
Console.WriteLine($"Ocean_proximity: {@"NEAR BAY"}");


// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Median_house_value: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

